name: Multi-Platform Matrix Build (5745c2d)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # Matrix strategy with 3 versions of Python
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: matrix-5745c2d
        run: echo "Building for Python ${{ matrix.python-version }}"

      - name: Generate build artifact
        run: |
          echo "Build output for Python version ${{ matrix.python-version }}" > build_output.txt
          echo "Timestamp: $(date)" >> build_output.txt
          echo "Python version: ${{ matrix.python-version }}" >> build_output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-5745c2d-py${{ matrix.python-version }}
          path: build_output.txt
